import { createFileRoute } from "@tanstack/react-router";
import { Braces, ChevronDown, ChevronUp, FileJson, Layers3, WandSparkles } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ErrorNotice, PageHeader, Spinner, ToolPage } from "@/components/edugenie/shared";
import { structureContent, type StructureResponse } from "@/services/api";
const description = "Organize raw study notes into topics, key points, definitions, examples, and a summary.";
export const Route = createFileRoute("/structure")({ head: () => ({ meta: [{ title: "Smart Content Structurer — EduGenie" }, { name: "description", content: description }, { property: "og:title", content: "Smart Content Structurer — EduGenie" }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: StructurePage });
function StructurePage() { const [text, setText] = useState(""); const [result, setResult] = useState<StructureResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [jsonOpen, setJsonOpen] = useState(false);
async function submit(event: FormEvent) { event.preventDefault(); if (!text.trim()) { setError("Please paste some raw notes to structure."); return; } setLoading(true); setError(""); setResult(null); setJsonOpen(false); try { setResult(await structureContent(text.trim())); } catch (err) { setError(err instanceof Error ? err.message : "Unable to connect to EduGenie. Please check the backend and try again."); } finally { setLoading(false); } }
return <ToolPage><PageHeader eyebrow="Organization tool" title="Organize Your Study Material" description="Turn raw notes into structured learning content." icon={Layers3} />{!result ? <form onSubmit={submit} className="rounded-2xl border bg-card p-5 shadow-soft sm:p-7"><label><span className="label">Raw notes</span><Textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Paste your raw notes here..." className="min-h-72 resize-y leading-6" /></label><Button type="submit" size="lg" className="mt-6" disabled={loading}>{loading ? <><Spinner />Structuring content...</> : <><WandSparkles />Structure Content</>}</Button>{error && <ErrorNotice message={error} />}</form> : <div className="space-y-5"><div className="rounded-2xl border bg-card p-6 shadow-soft"><p className="text-xs font-bold uppercase text-primary">Structured material</p><h2 className="mt-2 text-3xl font-bold">{result.title}</h2><div className="mt-5 flex flex-wrap gap-2">{result.topics.map((topic) => <span key={topic} className="rounded-full bg-accent px-3 py-1.5 text-xs font-semibold text-accent-foreground">{topic}</span>)}</div></div>
<div className="grid gap-5 lg:grid-cols-2"><ResultBlock title="Key Points"><ul className="space-y-3">{result.key_points.map((point) => <li key={point} className="flex gap-3 text-sm leading-6"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary" />{point}</li>)}</ul></ResultBlock><ResultBlock title="Definitions"><dl className="space-y-4">{result.definitions.map((item) => <div key={item.term}><dt className="font-semibold text-primary">{item.term}</dt><dd className="mt-1 text-sm leading-6 text-muted-foreground">{item.meaning}</dd></div>)}</dl></ResultBlock><ResultBlock title="Examples"><ol className="space-y-3">{result.examples.map((example, index) => <li key={example} className="flex gap-3 text-sm leading-6"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-accent text-xs font-bold text-primary">{index + 1}</span>{example}</li>)}</ol></ResultBlock><ResultBlock title="Summary"><p className="text-sm leading-7 text-muted-foreground">{result.summary}</p></ResultBlock></div>
<div className="rounded-xl border bg-card p-5 shadow-soft"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 font-semibold"><FileJson className="size-5 text-primary" />Raw response</div><Button variant="outline" size="sm" onClick={() => setJsonOpen((value) => !value)}><Braces />View JSON {jsonOpen ? <ChevronUp /> : <ChevronDown />}</Button></div>{jsonOpen && <pre className="mt-4 max-h-96 overflow-auto rounded-lg bg-code p-4 text-xs leading-5 text-code-foreground">{JSON.stringify(result, null, 2)}</pre>}</div><Button variant="outline" size="lg" onClick={() => { setResult(null); setError(""); }}>Structure Different Notes</Button></div>}</ToolPage>; }
function ResultBlock({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-card p-5 shadow-soft"><h3 className="mb-4 text-lg font-bold">{title}</h3>{children}</section>; }
