import { createFileRoute } from "@tanstack/react-router";
import { Check, Clipboard, Eraser, FileText, WandSparkles } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ErrorNotice, PageHeader, Spinner, ToolPage } from "@/components/edugenie/shared";
import { summarizeText } from "@/services/api";
const description = "Turn study material into a concise AI-generated summary with EduGenie.";
export const Route = createFileRoute("/summarize")({ head: () => ({ meta: [{ title: "Smart Summarizer — EduGenie" }, { name: "description", content: description }, { property: "og:title", content: "Smart Summarizer — EduGenie" }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: SummarizePage });
function SummarizePage() { const [text, setText] = useState(""); const [summary, setSummary] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
async function submit(event: FormEvent) { event.preventDefault(); if (!text.trim()) { setError("Please paste some study material to summarize."); return; } setLoading(true); setError(""); setSummary(""); try { const result = await summarizeText(text.trim()); setSummary(result.summary); } catch (err) { setError(err instanceof Error ? err.message : "Unable to connect to EduGenie. Please check the backend and try again."); } finally { setLoading(false); } }
async function copy() { await navigator.clipboard.writeText(summary); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
function clear() { setText(""); setSummary(""); setError(""); setCopied(false); }
return <ToolPage><PageHeader eyebrow="Reading tool" title="Smart Summarizer" description="Paste your study material and turn it into a clear, concise summary." icon={FileText} /><div className="grid gap-6 lg:grid-cols-2"><form onSubmit={submit} className="rounded-2xl border bg-card p-5 shadow-soft sm:p-7"><label><span className="label">Study material</span><Textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Paste your study material here..." className="min-h-72 resize-y leading-6" /></label><div className="mt-5 flex flex-wrap gap-3"><Button type="submit" size="lg" disabled={loading}>{loading ? <><Spinner />Summarizing...</> : <><WandSparkles />Summarize</>}</Button><Button type="button" size="lg" variant="outline" onClick={clear}><Eraser />Clear</Button></div>{error && <ErrorNotice message={error} />}</form><section className="min-h-96 rounded-2xl border bg-card p-5 shadow-soft sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-primary">Result</p><h2 className="mt-1 text-xl font-bold">Your summary</h2></div>{summary && <Button variant="outline" size="sm" onClick={copy}>{copied ? <Check /> : <Clipboard />}{copied ? "Copied" : "Copy Summary"}</Button>}</div>{summary ? <p className="mt-6 whitespace-pre-wrap text-sm leading-7 text-card-foreground">{summary}</p> : <div className="grid min-h-64 place-items-center text-center"><div><FileText className="mx-auto size-8 text-muted-foreground/50" /><p className="mt-3 text-sm text-muted-foreground">Your summary will appear here.</p></div></div>}</section></div></ToolPage>; }
