import { createFileRoute } from "@tanstack/react-router";
import { BrainCircuit, RefreshCw, Send } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ErrorNotice, PageHeader, Spinner, ToolPage } from "@/components/edugenie/shared";
import { askTutor } from "@/services/api";
const description = "Ask EduGenie a study question and receive a simple, step-by-step explanation.";
export const Route = createFileRoute("/tutor")({ head: () => ({ meta: [{ title: "AI Tutor — EduGenie" }, { name: "description", content: description }, { property: "og:title", content: "AI Tutor — EduGenie" }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: TutorPage });
function TutorPage() { const [question, setQuestion] = useState(""); const [subject, setSubject] = useState("General"); const [answer, setAnswer] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
async function submit(event: FormEvent) { event.preventDefault(); if (!question.trim()) { setError("Please enter a question for EduGenie."); return; } setLoading(true); setError(""); setAnswer(""); try { const result = await askTutor(question.trim(), subject); setAnswer(result.answer); } catch (err) { setError(err instanceof Error ? err.message : "Unable to connect to EduGenie. Please check the backend and try again."); } finally { setLoading(false); } }
function reset() { setQuestion(""); setAnswer(""); setError(""); }
return <ToolPage><PageHeader eyebrow="Explanation tool" title="Ask EduGenie" description="Ask questions and get simple, step-by-step explanations." icon={BrainCircuit} />{!answer ? <form onSubmit={submit} className="max-w-3xl rounded-2xl border bg-card p-5 shadow-soft sm:p-7"><label><span className="label">Your question</span><Textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask your doubt..." className="min-h-44 resize-y text-base leading-7" /></label><label className="mt-5 block max-w-sm"><span className="label">Subject <span className="font-normal text-muted-foreground">(optional)</span></span><Select value={subject} onValueChange={setSubject}><SelectTrigger className="h-11"><SelectValue /></SelectTrigger><SelectContent>{["Computer Science", "Programming", "Mathematics", "Electronics", "General"].map((item) => <SelectItem value={item} key={item}>{item}</SelectItem>)}</SelectContent></Select></label><Button type="submit" size="lg" className="mt-6" disabled={loading}>{loading ? <><Spinner />EduGenie is thinking...</> : <><Send />Ask EduGenie</>}</Button>{error && <ErrorNotice message={error} />}</form> : <section className="max-w-3xl rounded-2xl border bg-card p-5 shadow-soft sm:p-7"><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-primary text-primary-foreground"><BrainCircuit className="size-5" /></span><div><p className="text-xs font-bold uppercase text-primary">EduGenie response · {subject}</p><h2 className="mt-1 text-lg font-bold">{question}</h2></div></div><div className="mt-6 whitespace-pre-wrap border-l-2 border-primary/30 pl-5 text-sm leading-7 text-card-foreground">{answer}</div><Button size="lg" className="mt-7" onClick={reset}><RefreshCw />Ask Another Question</Button></section>}</ToolPage>; }
